config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include("website.urls")),
    path('account/', include("accounts.urls")),
    path('instructor/', include("instructor.urls")),
    path('exam/', include("exam_app.urls")),
    path('tutee/', include("tutee.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exam_app/urls.py
from django.urls import path
from . import views

app_name = "exam_app"
urlpatterns = [
    path('create-exam/', views.createExam, name="create-exam"),
    path('instructors/all-exams/', views.viewAllExamsInstructors, name="view-all-exams-instructors"),
    path('edit-exam/<int:exam_id>/', views.editExam, name="edit-exam"),
    path('edit-exam/<int:exam_id>/add-question/', views.addQuestion, name="add-question"),
    path('edit-exam/<int:exam_id>/edit-question/<int:question_id>/', views.EditQuestion, name="edit-question"),
    path('tutee/all-exams/', views.viewAllExamsTutee, name="view-all-exams-tutee"),
    path('view-exam/<int:exam_id>/', views.viewExam, name="view-exam"),
    path('exam-summary/<int:exam_details_id>', views.examSummary, name="exam-summary"),
    path('exam-result/<int:exam_details_id>', views.examResult, name="exam-result"),
    path('exam-results-list/<int:exam_id>', views.examResultsList, name="tutee-exam-results-list"),
    path('<int:exam_details_id>/view_question_result/<int:question_details>', views.questionResult,
         name="question-result"),
    path('edit-exam/edit-details/<int:exam_id>', views.editExamDetails, name="edit-details"),
    path('instructor/<int:exam_id>/results/', views.viewAllDetails, name="instructor-details"),
    path('instructor/<int:exam_id>/results/<int:exam_details_id>', views.tuteeExamDetails, name="tutee-exam-results"),
    path('exam/<int:exam_details_id>/evaluation/<int:question_details_id>', views.questionEvaluation,
         name='question-evaluation'),
    path('edit-exam/<int:exam_id>/add-section/', views.addSection, name="add-section"),
    path('edit-exam/<int:exam_id>/edit-section/<int:section_id>', views.editSection, name="edit-section"),
    path('edit-exam/<int:exam_id>/section/<int:section_id>/add-question', views.sectionAddQuestion,
         name="section-add-question"),
    path('edit-exam/<int:exam_id>/section/<int:section_id>/edit-question/<int:question_id>', views.sectionEditQuestion,
         name="section-edit-question"),
    path('<int:exam_id>/<int:section_index>/<int:question_index>', views.takeExamSection, name="take-exam-section"),
]

tutee/urls.py
from django.urls import path
from . import views

app_name = "tutee"
urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard"),
]

exam_app/forms.py
from django import forms
from django.forms import ModelForm
from .models import *


class MakeExamForm(ModelForm):
    title = forms.CharField(max_length=124)
    subject = forms.CharField(max_length=64)
    level = forms.CharField(max_length=64)
    date_time = forms.DateTimeField(required=False)
    duration = forms.DurationField(required=False)
    min_pass_points = forms.IntegerField(required=False)
    status = forms.CharField(required=False)
    username = forms.CharField(required=False)
    has_sections = forms.CharField()
    multiple_attempts = forms.CharField()

    class Meta:
        model = MakeExam
        fields = (
            'title', 'subject', 'level', 'date_time', 'duration', 'min_pass_points', 'has_sections',
            'multiple_attempts')
        exclude = ['owner', 'instructions']


class AddExamInstructionsForm(ModelForm):
    class Meta:
        model = MakeExam
        fields = ('instructions',)


class MakeQuestionForm(ModelForm):
    question_type = forms.CharField(max_length=64)
    max_time = forms.DurationField(required=False)
    max_points = forms.IntegerField(required=False)
    difficulty_level = forms.CharField(max_length=64, required=False)

    class Meta:
        model = MakeQuestion
        fields = ('question_type', 'question_text', 'max_time', 'max_points', 'difficulty_level')
        exclude = ['owner']


class MakeSectionForm(ModelForm):
    class Meta:
        model = MakeSection
        fields = ('title', 'sub_title', 'instructions', 'description')
        exclude = ['owner', 'exam']

exam_app/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import *
from .models import *
from .functions import *
from datetime import datetime
from django.contrib.auth.models import User
from datetime import timedelta


# Create your views here.
@login_required
def createExam(request):
    if not request.user.is_staff:
        redirect('website:permission-denied')

    if request.method == 'POST':
        make_exam_form = MakeExamForm(request.POST)
        if make_exam_form.is_valid():
            exam = make_exam_form.save(commit=False)
            exam.owner = request.user
            exam.save()
            exam_id = exam.id
            return redirect('exam_app:edit-exam', exam_id)
        else:
            content = {
                'title': request.POST['title'],
                'subject': request.POST['subject'],
                'level': request.POST['level'],
                'date': request.POST['date'],
                'time': request.POST['time'],
                'duration': request.POST['duration'],
                'min_pass_points': request.POST['min_pass_points'],
                'title_error': '',
                'subject_error': '',
                'level_error': '',
                'date_error': '',
                'time_error': '',
                'duration_error': '',
                'min_pass_points_error': '',
                'has_sections_error': '',
                'multiple_attempts_error': ''
            }
            for error in make_exam_form.errors:
                label = error + '_error'
                content[label] = make_exam_form.errors[error]
            return render(request, 'exam_app/instructor-create-exam.html', content)
    else:
        return render(request, 'exam_app/instructor-create-exam.html')


@login_required
def editExam(request, exam_id):
    exam = MakeExam.objects.get(id=exam_id)
    if not request.user.is_staff or exam.owner != request.user:
        redirect('website:permission-denied')

    if request.method == 'POST':
        if 'add_instructions' in request.POST:
            exam.instructions = request.POST['instructions']
            exam.save()
        if 'delete_question' in request.POST:
            delete_question_id = request.POST['delete_question']
            question = MakeQuestion.objects.get(id=delete_question_id)
            if question.owner == request.user:
                question.delete()

        if 'delete_section' in request.POST:
            delete_section_id = request.POST['delete_section']
            section = MakeSection.objects.get(id=delete_section_id)
            if section.owner == request.user:
                MakeQuestion.objects.filter(section=section).delete()
                section.delete()

        if 'publish-exam' in request.POST:
            exam = MakeExam.objects.get(id=exam_id)
            exam.status = 'Published'
            exam.save()

        if 'un-publish-exam' in request.POST:
            exam = MakeExam.objects.get(id=exam_id)
            exam.status = 'Draft'
            exam.save()

        if 'delete_exam' in request.POST:
            MakeQuestion.objects.filter(exam__id=exam_id).delete()
            MakeExam.objects.get(id=exam.id).delete()
            return redirect('exam_app:view-all-exams-instructors')

    questions_list = MakeQuestion.objects.filter(exam__id=exam_id)
    sections_list = MakeSection.objects.filter(exam=exam)
    instructions_form = AddExamInstructionsForm(instance=exam)
    return render(request, 'exam_app/instructor-edit-exam.html', {
        'exam': exam,
        'questions': questions_list,
        'sections': sections_list,
        'instructions_form': instructions_form,
    })


@login_required
def addOptionsAnswers(request, question):
    if not request.user.is_staff:
        redirect('website:permission-denied')

    option_count = 0
    answer_count = 0
    for field in request.POST:
        if 'option' in field:
            option_count += 1
            text = request.POST[field]
            option = Option.objects.create(option=text, question=question, index=option_count)
            option.save()
        elif 'answer' in field:
            answer_count += 1
            text = request.POST[field]
            if question.question_type == 'Multiple Choice - Multiple Answers':
                correct_option = request.POST[field]
                text = request.POST[correct_option]
            answer = Answer.objects.create(answer=text, question=question, index=answer_count)
            answer.save()

    if question.max_points == 0 or question.max_points is None:
        question.max_points = answer_count
        question.save()

    return answer_count


@login_required
def addQuestion(request, exam_id):
    if not request.user.is_staff:
        redirect('website:permission-denied')

    if request.method == 'POST':
        btn_action = request.POST['btn_action']
        make_question_form = MakeQuestionForm(request.POST)
        if make_question_form.is_valid():
            question = make_question_form.save(commit=False)
            question.owner = request.user
            question.max_points = 0
            question.save()

            if question.question_type == 'Multiple Choice - Multiple Answers' or question.question_type == 'Fill In The Blanks':
                question.evaluation_type = True
            else:
                question.evaluation_type = False

            question.exam.add(exam_id)
            question.save()
            addOptionsAnswers(request, question)

            if question.max_points == 0 or question.max_points is None:
                question.max_points = 1
                question.save()

            if btn_action == 'add':
                return redirect('exam_app:add-question', exam_id)
            elif btn_action == 'save':
                return redirect('exam_app:edit-exam', exam_id)
        else:
            return render(request, 'exam_app/instructor-add-question.html', {
                'exam_id': exam_id,
                'make_question_form': make_question_form,
            })
    else:
        question_form = MakeQuestionForm()
        return render(request, 'exam_app/instructor-add-question.html', {
            'exam_id': exam_id,
            'question_form': question_form,
        })


@login_required
def viewAllExamsInstructors(request):
    if not request.user.is_staff:
        redirect('website:permission-denied')

    if request.method == 'POST':
        if 'publish' in request.POST:
            exam_id = request.POST['publish']
            exam = MakeExam.objects.get(id=exam_id)
            exam.status = 'Published'
            exam.save()

        if 'un-publish' in request.POST:
            exam_id = request.POST['un-publish']
            exam = MakeExam.objects.get(id=exam_id)
            exam.status = 'Draft'
            exam.save()

    exams = MakeExam.objects.filter(owner=request.user)
    return render(request, 'exam_app/instructor-view-all-exams.html', {
        'exams': exams,
    })


@login_required
def editExamDetails(request, exam_id):
    exam = MakeExam.objects.get(id=exam_id)
    previous_section_details = exam.has_sections
    if not request.user.is_staff or exam.owner != request.user:
        redirect('website:permission-denied')

    if request.method == 'POST':
        exam_form = MakeExamForm(request.POST, instance=exam)
        if exam_form.is_valid():
            current_section_details = request.POST['has_sections']

            if str(previous_section_details) != str(current_section_details):
                if str(previous_section_details) == 'True':
                    MakeSection.objects.filter(exam=exam, owner=request.user).delete()
                else:
                    questions = MakeQuestion.objects.filter(exam=exam)
                    if len(questions) != 0:
                        MakeSection.objects.create(owner=request.user, exam=exam, title='All Questions').save()
                        section = MakeSection.objects.get(owner=request.user, exam=exam, title='All Questions')
                        for question in questions:
                            question.section.add(section.id)
                            question.save()
            details = exam_form.save(commit=False)
            details.owner = request.user
            details.save()
        return redirect("exam_app:edit-exam", exam_id=exam_id)
    return render(request, 'exam_app/instructor-edit-exam-details.html', {
        'exam': exam,
        'exam_duration': convertTimeString(str(exam.duration))
    })


@login_required
def EditQuestion(request, exam_id, question_id):
    question_model = MakeQuestion.objects.get(id=question_id)
    if not request.user.is_staff or question_model.owner != request.user:
        redirect('website:permission-denied')

    if request.method == 'POST':
        make_question_form = MakeQuestionForm(request.POST, instance=question_model)
        if make_question_form.is_valid():
            question = make_question_form.save(commit=False)
            question.max_points = request.POST['max_points']
            question.owner = request.user
            question.save()
            if question.question_type == 'Multiple Choice - Multiple Answers' or question.question_type == 'Fill In The Blanks':
                question.evaluation_type = True
            else:
                question.evaluation_type = False
            question.exam.add(exam_id)
            question.save()
            Option.objects.filter(question=question).delete()
            Answer.objects.filter(question=question).delete()
            addOptionsAnswers(request, question)
            if question.max_points == 0 or question.max_points is None:
                question.max_points = 1
                question.save()

    # End of post if exists

    question = MakeQuestion.objects.get(id=question_id)

templates/exam_app/create-exam.html
{% extends 'exam_app/base.html' %}

{% block title %}
    Tutest - Create Exam
{% endblock %}

{% block styles %}
{% endblock %}

{% block body %}
    <div class="p-5">
        <h3 class="py-3"><strong>New Exam Details:</strong></h3>
        <form action="{% url 'exam_app:create-exam' %}" method="post">
            {% csrf_token %}
            <small class="form-text custom-error-message">{{ error_message }}</small>
            {{ error_message }}
            <div class="row m-0 my-2">
                <div class="form-group">
                    <label class="py-2" for="input-1">Title</label>
                    <input type="text" class="form-control" id="input-1" placeholder="Title" name="title"
                           value="{{ title }}">
                    <small class="form-text custom-error-message">{{ title_error }}</small>
                </div>
            </div>
            <div class="row m-0 my-2">
                <div class="form-group col-md-6">
                    <label class="py-2" for="input-2">Subject</label>
                    <input type="text" class="form-control" id="input-2" placeholder="Subject" name="subject"
                           value="{{ subject }}">
                    <small class="form-text custom-error-message">{{ subject_error }}</small>

                </div>
                <div class="form-group col-md-6">
                    <label class="py-2" for="input-3">Class/Level</label>
                    <input type="text" class="form-control" id="input-3" placeholder="Class/Level" name="level"
                           value="{{ level }}">
                    <small class="form-text custom-error-message">{{ level_error }}</small>
                </div>
            </div>
            <div class="row m-0 my-2">
                <div class="form-group col-md-3">
                    <label class="py-2" for="input-4">Date</label>
                    <input type="date" class="form-control" id="input-4" placeholder="Title" name="date"
                           value="{{ date }}">
                    <small class="form-text custom-error-message">{{ date_error }}</small>
                </div>
                <div class="form-group col-md-3">
                    <label class="py-2" for="input-5">Time</label>
                    <input type="time" class="form-control" id="input-5" placeholder="HH:MM" name="time"
                           value="{{ time }}">
                    <small class="form-text custom-error-message">{{ time_error }}</small>
                </div>
                <div class="form-group col-md-3">
                    <label class="py-2" for="input-6">Duration</label>
                    <input type="time" step="1" class="form-control" id="input-6" placeholder="HH:MM:SS" name="duration"
                           value="{{ duration }}" aria-describedby="durationDescription">
                    <small id="durationDescription" class="form-text text-muted">
                        HH:MM:SS
                    </small>
                    <small class="form-text custom-error-message">{{ duration_error }}</small>
                </div>
                <div class="form-group col-md-3">
                    <label class="py-2" for="input-7">Min pass points</label>
                    <input type="number" class="form-control" id="input-7" placeholder="%" name="min_pass_points"
                           value="{{ min_pass_points }}"
                           min="0" max="100">
                    <small class="form-text custom-error-message">{{ min_pass_points_error }}</small>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <a href="{% url 'exam_app:view-all-exams-instructors' %}">
                        <button class="btn btn-primary" type="button" name="btn_action" value="">View Exams</button>
                    </a>
                </div>
                <div class="col text-end">
                    <button class="btn btn-primary" type="submit" name="btn_action" value="">Create Exam</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/exam_app/instructor-view-all-exams.html
{% extends 'exam_app/base.html' %}

{% block title %}
{% endblock %}

{% block styles %}
{% endblock %}

{% block body %}
    <div class="p-5">
        <form action="{% url 'exam_app:view-all-exams-instructors' %}" method="POST">
            {% csrf_token %}
            <h4><strong>List Of Exams Created By You</strong></h4>
            <hr>
            <table class="table align-middle text-center">
                <thead class="thead-dark text-center">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Class/Level</th>
                    <th scope="col">Date & Time</th>
                    <th scope="col">Duration</th>
                    <th scope="col">Status</th>
                    <th scope="col">Exam Page</th>
                    <th scope="col">Change Status</th>
                    <th scope="col">Results</th>
                </tr>
                </thead>
                <tbody>
                {% for exam in exams %}
                    <tr class="">
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ exam.title }}</td>
                        <td>{{ exam.subject }}</td>
                        <td>{{ exam.level }}</td>
                        <td>{{ exam.date_time }}</td>
                        <td>{{ exam.duration }}</td>
                        <td>{{ exam.status }}</td>
                        <td>
                            <a href="{% url 'exam_app:edit-exam' exam.id %}">
                                <button type="button" class="btn btn-primary btn-sm">View/Edit</button>
                            </a>
                        </td>
                        <td>
                            {% if exam.status == 'Published' %}
                                <button class="btn btn-danger btn-sm" type="submit" name="un-publish"
                                        value="{{ exam.id }}">Unpublish
                                </button>
                            {% else %}
                                <button class="btn btn-success btn-sm" type="submit" name="publish"
                                        value="{{ exam.id }}">
                                    Publish
                                </button>
                            {% endif %}
                        </td>
                        <td>
                            <a href="{% url 'exam_app:instructor-details' exam.id %}">
                                <button type="button" class="btn btn-primary btn-sm">Results</button>
                            </a>
                        </td>
                    </tr>

                {% endfor %}
                </tbody>
            </table>
        </form>
        <div class="row">
            <div class="col my-3">
                <a href="{% url 'exam_app:create-exam' %}">
                    <button type="button" class="btn btn-success">+ Create Exam</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

templates/exam_app/instructors-question-evaluation.html
{% extends 'exam_app/base.html' %}

{% block title %}
    Title - Student's Evaluation
{% endblock %}

{% block styles %}
{% endblock %}

{% block body %}
    <div class="p-5">
        <h3><strong>{{ question.question_type }}</strong></h3>
        <hr>
        <h5><strong>Question</strong>:</h5>
        <p>{{ question.question_text | safe }}</p>
        <hr>
        <h5>Student Answer:</h5>
        <ul>
            {% for user_input in user_inputs %}
                <li>{{ user_input.answer_text_input }}</li>
            {% endfor %}
            {% for user_upload in user_uploads %}
                <li><a href="{{ user_upload.answer_text_input.url }}" download>
                    Download file</a>
                </li>
            {% endfor %}
        </ul>
        <hr>
        {% if user_question_details.evaluation_status != 'Evaluated' %}
            <h5>Evaluation Area:</h5>
            <form action="{% url 'exam_app:question-evaluation' exam_details_id question_details_id %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-4">
                        <label class="form-label" for="questionType">User Answer Result </label>
                        <select name="result" id="questionType" class="form-select">
                            <option value="Pending" hidden selected>Select from list</option>
                            <option value="Correct">Correct</option>
                            <option value="Pending">Pending</option>
                            <option value="Incorrect">Incorrect</option>
                        </select>
                    </div>
                    <div class="col-md-4">
                        <label class="form-label" for="questionPoints">Points </label>
                        <select name="points" id="questionPoints" class="form-select">
                            <option value="0" hidden selected>Select from list</option>
                            <option value=0>0</option>
                            {% with ''|center:question.max_points as range %}
                                {% for _ in range %}
                                    <option value="{{ forloop.counter }}">{{ forloop.counter }}</option>
                                {% endfor %}
                            {% endwith %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="py-2" for="input-1">Remark</label>
                        <textarea class="form-control edit-exam" name="remark" id="input-1" cols="" rows="3"
                                  placeholder="Type in your remark"></textarea>
                    </div>
                </div>
                <hr>
                <div class="text-end">
                    <button type="submit" class="btn btn-primary mx-3">
                        Save
                    </button>
                    <a href="{% url 'exam_app:tutee-exam-results' exam.id exam_details_id %}">
                        <button type="button" class="btn btn-primary">
                            Exit without saving
                        </button>
                    </a>
                </div>
            </form>
        {% else %}
            <form action="{% url 'exam_app:question-evaluation' exam_details_id question_details_id %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-4">
                        <label class="form-label" for="userQuestionResult">User Answer Result </label>
                        <select name="result" id="userQuestionResult" class="form-select" disabled>
                            <option value="{{ user_result.result }}" hidden
                                    selected>{{ user_result.result }}</option>
                            <option value="Correct">Correct</option>
                            <option value="Pending">Pending</option>
                            <option value="Incorrect">Incorrect</option>
                        </select>
                    </div>
                    <div class="col-md-4">
                        <label class="form-label" for="questionPoints">Points</label>
                        <select name="points" id="questionPoints" disabled class="form-select">
                            <option value="{{ user_question_details.points }}" hidden
                                    selected>{{ user_question_details.points }}</option>
                            <option value=0>0</option>
                            {% with ''|center:question.max_points as range %}
                                {% for _ in range %}
                                    <option value="{{ forloop.counter }}">{{ forloop.counter }}</option>
                                {% endfor %}
                            {% endwith %}
                        </select>
                    </div>

                    <div class="form-group">
                        <label class="py-2" for="input-1">Remark</label>
                        <textarea class="form-control edit-exam" name="remark" id="input-1" cols="" rows="3"
                                  placeholder="Type in your remark"
                                  disabled>{{ user_question_details.remark }}</textarea>
                    </div>
                </div>
                <hr>
                <div class="text-end">
                    <button id="edit-btn" type="button" class="btn btn-primary mx-3" onclick="editResults()">
                        Edit Result
                    </button>
                    <button id="save-btn" type="submit" class="btn btn-primary mx-3" name="save_evaluation"
                            value="save" hidden>
                        Save
                    </button>
                    <a href="{% url 'exam_app:tutee-exam-results' exam.id exam_details_id %}">
                        <button type="button" class="btn btn-primary">
                            Student Result Page
                        </button>
                    </a>
                </div>
            </form>
        {% endif %}
        <hr>

    </div>
{% endblock %}

{% block script %}
    <script>
        function editResults() {
            let edit_btn = document.getElementById('edit-btn')
            edit_btn.style.visibility = "hidden"
            document.getElementById('save-btn').removeAttribute("hidden");
            document.getElementById('input-1').removeAttribute("disabled");
            document.getElementById('userQuestionResult').removeAttribute("disabled");
            document.getElementById('questionPoints').removeAttribute("disabled");
        }
    </script>
{% endblock %}

templates/exam_app/tutee-exam-results.html
{% extends 'exam_app/base.html' %}
{% load custom_time_delta %}

{% block title %}
    Tutest - {{ exam.title }} Results
{% endblock %}

{% block styles %}
{% endblock %}

{% block body %}
    <div class="p-5">
        <div class="row">
            <div class="col">
                <h4><strong>{{ exam.title }}</strong></h4>
                <h5>{{ exam.subject }} | {{ exam.level }}</h5>
            </div>
            <div class="col text-end my-auto">
                <a href="{% url 'exam_app:view-all-exams-tutee' %}">
                    <button type="button" class="btn btn-primary">View all Exams</button>
                </a>
            </div>
        </div>
        <hr>
        {% if all_exam_details %}
            <table class="table align-middle">
                <thead class="thead-dark">
                <tr class="text-center">
                    <th scope="col">#</th>
                    <th scope="col">Date & Time</th>
                    <th scope="col">Status</th>
                    <th scope="col">Result</th>
                    <th scope="col">Points</th>
                    <th scope="col">Time Elapsed</th>
                    <th scope="col">View</th>
                </tr>
                </thead>
                <tbody>
                {% for exam_details in all_exam_details %}
                    <tr class="text-center">
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ exam_details.date }}</td>
                        <td>{{ exam_details.status }}</td>
                        <td>{{ exam_details.result_status }}</td>
                        <td>{{ exam_details.overall_points }}</td>
                        <td>{{ exam_details.time_elapsed|timeDelta }}</td>
                        <td>
                            <a href="{% url 'exam_app:exam-result' exam_details.id %}">
                                <button type="button" class="btn btn-primary btn-sm">View</button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <hr>
            {% if exam.multiple_attempts %}
                <h6>Click below to retake the exam</h6>
                <a href="{% url 'exam_app:view-exam' exam.id %}">
                    <button type="button" class="btn btn-primary">Retake Exam</button>
                </a>
            {% endif %}
            <a href="{% url 'exam_app:view-exam' exam.id %}">
            </a>

        {% else %}
            <h5>You haven't attempted this exam. Click below to view the exam</h5>
            <hr>
            <a href="{% url 'exam_app:view-exam' exam.id %}">
                <button type="button" class="btn btn-success">Take Exam</button>
            </a>
        {% endif %}

    </div>
{% endblock %}

{% block script %}
{% endblock %}