accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = "account"
urlpatterns = [
    path('sign-up/', views.signUpAs, name="sign-up-as"),
    # path('sign-up/instructor/', views.instructorSignUp, name="sign-up-as-instructor"),
    path('sign-up/tutee/', views.tuteeSignUp, name="sign-up-as-tutee"),
    path('sign-in/', LoginView.as_view(template_name='accounts/sign-in.html'), name="sign-in"),
    path('sign-out/', LogoutView.as_view(), name="sign-out"),
    path('forgot-password/', views.forgotPassword, name="forgot-password"),
    path('change-password/<token>', views.changePassword, name="change-password"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include("website.urls")),
    path('account/', include("accounts.urls")),
    path('instructor/', include("instructor.urls")),
    path('exam/', include("exam_app.urls")),
    path('tutee/', include("tutee.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exam_app/urls.py
from django.urls import path
from . import views

app_name = "exam_app"
urlpatterns = [
    path('create-exam/', views.createExam, name="create-exam"),
    path('instructors/all-exams/', views.viewAllExamsInstructors, name="view-all-exams-instructors"),
    path('edit-exam/<int:exam_id>/', views.editExam, name="edit-exam"),
    path('edit-exam/<int:exam_id>/add-question/', views.addQuestion, name="add-question"),
    path('edit-exam/<int:exam_id>/edit-question/<int:question_id>/', views.EditQuestion, name="edit-question"),
    path('tutee/all-exams/', views.viewAllExamsTutee, name="view-all-exams-tutee"),
    path('view-exam/<int:exam_id>/', views.viewExam, name="view-exam"),
    path('exam-summary/<int:exam_details_id>', views.examSummary, name="exam-summary"),
    path('exam-result/<int:exam_details_id>', views.examResult, name="exam-result"),
    path('exam-results-list/<int:exam_id>', views.examResultsList, name="tutee-exam-results-list"),
    path('<int:exam_details_id>/view_question_result/<int:question_details>', views.questionResult,
         name="question-result"),
    path('edit-exam/edit-details/<int:exam_id>', views.editExamDetails, name="edit-details"),
    path('instructor/<int:exam_id>/results/', views.viewAllDetails, name="instructor-details"),
    path('instructor/<int:exam_id>/results/<int:exam_details_id>', views.tuteeExamDetails, name="tutee-exam-results"),
    path('exam/<int:exam_details_id>/evaluation/<int:question_details_id>', views.questionEvaluation,
         name='question-evaluation'),
    path('edit-exam/<int:exam_id>/add-section/', views.addSection, name="add-section"),
    path('edit-exam/<int:exam_id>/edit-section/<int:section_id>', views.editSection, name="edit-section"),
    path('edit-exam/<int:exam_id>/section/<int:section_id>/add-question', views.sectionAddQuestion,
         name="section-add-question"),
    path('edit-exam/<int:exam_id>/section/<int:section_id>/edit-question/<int:question_id>', views.sectionEditQuestion,
         name="section-edit-question"),
    path('<int:exam_id>/<int:section_index>/<int:question_index>', views.takeExamSection, name="take-exam-section"),
]

tutee/urls.py
from django.urls import path
from . import views

app_name = "tutee"
urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard"),
]

website/urls.py
from django.urls import path
from . import views

app_name = "website"
urlpatterns = [
    path('', views.index, name="index"),
    path('support-center/', views.supportCenter, name="support-center"),
    path('support-center/success', views.supportCenterSuccess, name="support-center-success"),
    path('permission-denied', views.permissionDenied, name="permission-denied")

]

exam_app/models.py
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


class MakeExam(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=124)
    subject = models.CharField(max_length=64)
    level = models.CharField(max_length=64)
    date_time = models.DateTimeField(null=True)
    duration = models.DurationField(null=True)
    min_pass_points = models.IntegerField(null=True)
    status = models.CharField(max_length=64, blank=True, default='Draft')
    has_sections = models.BooleanField(default=False)
    multiple_attempts = models.BooleanField(default=False)
    instructions = RichTextUploadingField(blank=True, default="")

    def __str__(self):
        return self.title


class MakeSection(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=124, blank=True)
    sub_title = models.CharField(max_length=124, blank=True)
    instructions = RichTextUploadingField(blank=True, default="")
    description = RichTextUploadingField(blank=True, default="")
    exam = models.ForeignKey('MakeExam', blank=True, on_delete=models.CASCADE)


class MakeQuestion(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    question_text = RichTextUploadingField()
    question_type = models.CharField(max_length=64)
    max_time = models.DurationField(null=True)
    max_points = models.IntegerField(default=1)
    difficulty_level = models.CharField(max_length=64, default="None", null=True)
    exam = models.ManyToManyField('MakeExam')
    evaluation_type = models.BooleanField(default=False)
    section = models.ManyToManyField('MakeSection', default="", blank=True)

    def __str__(self):
        return self.question_type


class Option(models.Model):
    option = models.CharField(max_length=124)
    index = models.IntegerField(default=1)
    question = models.ForeignKey('MakeQuestion', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.option}-{self.index}"


class Answer(models.Model):
    answer = models.CharField(max_length=124)
    index = models.IntegerField(default=1)
    question = models.ForeignKey('MakeQuestion', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.answer}-{self.index}"


class UserExamDetails(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    exam = models.ForeignKey('MakeExam', on_delete=models.CASCADE)
    status = models.CharField(max_length=64, default='Yet To Take')
    result_status = models.CharField(max_length=64, blank=True, null=True)
    overall_points = models.IntegerField(blank=True, null=True)
    start_time = models.TimeField(null=True, default=None)
    end_time = models.TimeField(null=True, default=None)
    time_elapsed = models.DurationField(null=True)
    date = models.DateTimeField(auto_now=True, null=True)


class UserQuestionDetails(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey('MakeQuestion', on_delete=models.CASCADE)
    exam_details = models.ForeignKey('UserExamDetails', on_delete=models.CASCADE)
    points = models.IntegerField(blank=True, default=0)
    evaluation_status = models.CharField(max_length=64, blank=True, null=True)
    start_time = models.DateTimeField(null=True, default=None)
    end_time = models.DateTimeField(null=True, default=None)
    time_elapsed = models.DurationField(null=True)
    remark = models.TextField(default='', blank=True)


class UserAnswerTextInput(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey('UserQuestionDetails', on_delete=models.CASCADE)
    answer_text_input = models.TextField(blank=True, null=True)
    index = models.IntegerField(blank=True, null=True)


class UserAnswerFileUpload(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey('UserQuestionDetails', on_delete=models.CASCADE)
    answer_text_input = models.FileField(null=True)
    index = models.IntegerField(blank=True, null=True)


@receiver(post_delete, sender=UserAnswerFileUpload)
def post_save_image(sender, instance, *args, **kwargs):
    """ Clean Old Image file """
    try:
        instance.answer_text_input.delete(save=False)
    finally:
        pass


class UserResults(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    question_type = models.CharField(max_length=64)
    exam_details = models.ForeignKey('UserExamDetails', on_delete=models.CASCADE)
    question_details = models.ForeignKey('UserQuestionDetails', on_delete=models.CASCADE)
    question = models.ForeignKey('MakeQuestion', on_delete=models.CASCADE)
    status = models.CharField(max_length=64)
    result = models.CharField(max_length=64)
    points = models.IntegerField(blank=True, null=True)
    time_elapsed = models.DurationField(null=True)

tutee/models.py
from django.db import models

# Create your models here.

tutee/views.py
from django.shortcuts import render
from exam_app.models import *
from datetime import timedelta
import datetime


# Create your views here.
def dashboard(request):
    today = datetime.datetime.now()
    five_hrs_back = today - datetime.timedelta(hours=5)
    mock_exams = MakeExam.objects.filter(multiple_attempts=True, status='Published')
    upcoming_exams = MakeExam.objects.filter(multiple_attempts=False, status='Published', date_time__gte=today)
    exams_list = MakeExam.objects.filter(multiple_attempts=False, status='Published', date_time__gte=five_hrs_back,
                                         date_time__lt=today)

    ongoing_exams = []
    for exam in exams_list:
        if (today - exam.duration) < exam.date_time:
            ongoing_exams.append(exam)

    return render(request, 'tutee/dashboard.html', {
        'mock_exams': mock_exams,
        'upcoming_exams': upcoming_exams,
        'ongoing_exams': ongoing_exams,
    })

templates/tutee/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
    {% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon_io/favicon.ico' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block styles %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand sticky-top">
        <div class="container-xxl px-3">
            <a class="navbar-brand" href="{% url 'website:index' %}">
                <img src="{% static 'images/light-logo.png' %}" alt="Tutest Logo" height="57px" width="137px">
            </a>
            <ul class="navbar-nav ms-auto align-items-center">
                {#<li class="nav-item"><a class="nav-link mx-2" href="#">Features</a></li>#}
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="true">
                        <button class="btn btn-light profile-btn" type="button">{{ user.username.0.upper }}</button>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li class="text-end px-3"><strong>Hi, {{ user.first_name }}</strong></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li class=text-end px-3
                        "><a class="dropdown-item" href="{% url 'account:sign-out' %}">Sign out</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
    <main class="container-xxl px-3">
        {% block body %}
        {% endblock %}
    </main>
    <footer>
        <div class="container-xxl p-3 text-center">
            <small class="footer-copyright">&copy; TUTEST 2022</small>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
</body>
</html>

templates/tutee/dashboard.html
{% extends 'tutee/base.html' %}

{% block title %}
    Tutest - Dashboard
{% endblock %}

{% block styles %}
{% endblock %}

{% block body %}
    <div class="p-3">
        <div class="row">
            <div class="col-9 my-auto">
                <h6 class="m-0"><strong>Welcome {{ user.first_name }} {{ user.last_name }}</strong></h6>
            </div>
            <div class="col-3 text-end">
                <a href="{% url 'exam_app:view-all-exams-tutee' %}">
                    <button class="btn btn-primary btn-sm" type="button" name="btn_action" value="">All Exams</button>
                </a>
            </div>
        </div>
        <hr>
        <div class="row">
            {% if ongoing_exams %}
                <div class="col p-3">
                    <h4>Open/Ongoing Exams</h4>
                    <table class="table table-striped border rounded text-center">
                        <thead>
                        <tr>
                            <th scope="col">Title</th>
                            <th scope="col">Subject</th>
                            <th scope="col">Date & Time</th>
                            <th scope="col">Duration</th>
                            <th scope="col">No of Sections</th>
                            <th scope="col">No of Questions</th>
                            <th scope="col">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for ongoing_exam in ongoing_exams %}
                            <tr>
                                <th scope="row">{{ ongoing_exam.title }}</th>
                                <td>{{ ongoing_exam.subject }}</td>
                                <td>{{ ongoing_exam.date_time }}</td>
                                <td>{{ ongoing_exam.duration }}</td>
                                <td>{{ ongoing_exam.makesection_set.count }}</td>
                                <td>{{ ongoing_exam.makequestion_set.count }}</td>
                                <td>
                                    <a href="{% url 'exam_app:view-exam' ongoing_exam.id %}">
                                        <button type="button" class="btn btn-success btn-sm">Start Exam</button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <hr>
            {% endif %}
        </div>
        <div class="row">
            {% if mock_exams %}
                <div class="col-md-12 p-3">
                    <h4>Mock/Practice Exams</h4>
                    <table class="table table-striped border rounded text-center">
                        <thead>
                        <tr>
                            <th scope="col">Title</th>
                            <th scope="col">Subject</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for mock_exam in mock_exams %}
                            <tr>
                                <th scope="row">{{ mock_exam.title }}</th>
                                <td>{{ mock_exam.subject }}</td>
                                <td>
                                    <a href="{% url 'exam_app:view-exam' mock_exam.id %}">
                                        <button type="button" class="btn btn-success btn-sm">Practice</button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}
            {% if upcoming_exams %}
                <div class="col-md-12 p-3">
                    <h4>Upcoming Exams</h4>
                    <table class="table table-striped border rounded text-center">
                        <thead>
                        <tr>
                            <th scope="col">Title</th>
                            <th scope="col">Subject</th>
                            <th scope="col">Date & Time</th>
                            <th scope="col">View</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for upcoming_exam in upcoming_exams %}
                            <tr>
                                <th scope="row">{{ upcoming_exam.title }}</th>
                                <td>{{ upcoming_exam.subject }}</td>
                                <td>{{ upcoming_exam.date_time }}</td>
                                <td>
                                    <a href="{% url 'exam_app:view-exam' upcoming_exam.id %}">
                                        <button type="button" class="btn btn-success btn-sm">View</button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}
        </div>
        <hr>
    </div>
{% endblock %}