accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = "account"
urlpatterns = [
    path('sign-up/', views.signUpAs, name="sign-up-as"),
    # path('sign-up/instructor/', views.instructorSignUp, name="sign-up-as-instructor"),
    path('sign-up/tutee/', views.tuteeSignUp, name="sign-up-as-tutee"),
    path('sign-in/', LoginView.as_view(template_name='accounts/sign-in.html'), name="sign-in"),
    path('sign-out/', LogoutView.as_view(), name="sign-out"),
    path('forgot-password/', views.forgotPassword, name="forgot-password"),
    path('change-password/<token>', views.changePassword, name="change-password"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include("website.urls")),
    path('account/', include("accounts.urls")),
    path('instructor/', include("instructor.urls")),
    path('exam/', include("exam_app.urls")),
    path('tutee/', include("tutee.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutee/urls.py
from django.urls import path
from . import views

app_name = "tutee"
urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard"),
]

website/urls.py
from django.urls import path
from . import views

app_name = "website"
urlpatterns = [
    path('', views.index, name="index"),
    path('support-center/', views.supportCenter, name="support-center"),
    path('support-center/success', views.supportCenterSuccess, name="support-center-success"),
    path('permission-denied', views.permissionDenied, name="permission-denied")

]

website/models.py
from django.db import models


# Create your models here.
class UserContact(models.Model):
    date_time = models.DateTimeField(auto_now=True)
    category = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    message = models.TextField()
    is_open = models.BooleanField()

website/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import *
from .functions import *


# Create your views here.
def index(request):
    if request.user.is_staff:
        return redirect('instructor:dashboard')
    if request.user.is_active:
        return redirect('tutee:dashboard')
    return render(request, 'website/index.html')


def permissionDenied(request):
    return render(request, 'website/permission-denied.html')


def supportCenter(request):
    if request.method == 'POST':
        category = request.POST['subject']
        email = request.POST['email']
        message = request.POST['message']
        UserContact.objects.create(category=category, email=email, message=message, is_open=True)
        if sendUserCopy(request.POST):
            return redirect('website:support-center-success')
    return render(request, 'website/support-center.html')


def supportCenterSuccess(request):
    return render(request, 'website/support-center-success.html')

templates/website/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {# Website Favicon #}
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon_io/favicon.ico' %}">

    {# Bootstrap CSS CND link #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    {# Custom CSS Files #}
    <link rel="stylesheet" href="{% static 'css/website/base.css' %}">
    {% block styles %}
    {% endblock %}
</head>
<body>
    {# Navigation Bar #}
    <nav class="navbar navbar-expand sticky-top">
        <div class="container-xxl px-2">
            {# Website Logo #}
            <a class="navbar-brand" href="{% url 'website:index' %}">
                <img src="{% static 'images/light-logo.png' %}" alt="Tutest Logo" height="50px" width="120px">
            </a>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item my-auto">
                    <a class="nav-link" href="{% url 'website:support-center' %}">
                        Contact Us
                    </a>
                </li>
                <li class="nav-item  my-auto">
                    <a class="nav-link" href="{% url 'account:sign-in' %}">
                        <button class="btn btn-outline-light btn-sm" type="button">Sign in</button>
                    </a>
                </li>
                <li class="nav-item  my-auto">
                    <a class="nav-link" href="{% url 'account:sign-up-as' %}">
                        <button class="btn btn-light btn-sm" type="button">Sign up</button>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <main class="container-xxl">
        {% block body %}
        {% endblock %}
    </main>
    <footer>
        <div class="container-xxl py-4 text-center">
            <small>&copy; TUTEST 2022</small>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <script>
        if (window.history.replaceState) {
            window.history.replaceState(null, null, window.location.href);
        }
    </script>

</body>
</html>

templates/website/index.html
{% extends 'website/base.html' %}
{% load static %}

{% block title %}
    Tutest - Online Exam Platform
{% endblock %}

{% block styles %}
{% endblock %}


{% block body %}
    <section class="p-3 greeting">
        <div class="row m-0">
            <div class="col-md-6 my-auto p-2">
                <h1 class="curve-font mb-3">Hi,<br>Welcome to Tutest...</h1>
                <h3 class="curve-font mb-3">Your All-In-One Online Test Management System</h3>
                <h6 class="curve-font">A platform for all kinds of institutions/Organizations to conduct tests so that
                    their exam taker can
                    take the test from anywhere and at any time using a computer or a smartphone.</h6>
            </div>
            <div class="col-md-6 my-auto p-2 text-center">
                <img src="{% static 'images/website/home-page-main-pic.png' %}" alt="Online exam image">
            </div>
        </div>
    </section>
    <hr class="w-50 mx-auto">
    <section class="p-3">
        <h2 class="curve-font text-center mb-3">Features</h2>
        <div class="row justify-content-center">
            <div class="col-lg-3 col-sm-4 features-card p-3 m-3">
                <div class="features-icon mb-3">
                    <img src="{% static 'images/flaticon/computer.png' %}" alt="Computer Icon">
                </div>
                <p><strong>Computer Based Test</strong></p>
                <ul>
                    <li>Live exam tracking</li>
                    <li>Instant results</li>
                    <li>100% security of data</li>
                    <li>Vast variety of question types</li>
                    <li>Candidate can attend exam on smart mobile or table as well</li>
                </ul>
            </div>
            <div class="col-lg-3 col-sm-4 features-card p-3 m-3">
                <div class="features-icon mb-3">
                    <img src="{% static 'images/flaticon/webcam.png' %}" alt="Computer Icon">
                </div>
                <p><strong>Proctored Test</strong></p>
                <ul>
                    <li>Anti-cheat detection</li>
                    <li>Real-Time Candidate’s Photo Capturing</li>
                    <li>Live and recorded proctoring</li>
                    <li>secured platform</li>
                </ul>
            </div>
            <div class="col-lg-3 col-sm-4 features-card p-3 m-3">
                <div class="features-icon mb-3">
                    <img src="{% static 'images/flaticon/additional.png' %}" alt="Computer Icon">
                </div>
                <p><strong>Additional Features</strong></p>
                <ul>
                    <li>Integrate with in your LMS</li>
                    <li>Best fit for entrance/weekly/semester exams</li>
                    <li>Zero downtime in declaring results</li>
                    <li>Candidate’s insights</li>
                </ul>
            </div>
        </div>

    </section>
{% endblock %}

templates/website/permission-denied.html
{% extends 'website/base.html' %}

{% block title %}
{% endblock %}

{% block styles %}
{% endblock %}

{% block body %}
    <div class="p-5">
        <h4><strong class="errors">Permission Denied</strong></h4>
        <p class="errors">you are trying to access something which is out of your scope</p>
        <hr>
        <a href="{% url 'website:index' %}">
            <button type="button" class="btn btn-primary"> Back to Home</button>
        </a>
        <hr>
    </div>
{% endblock %}

templates/website/support-center-success.html
{% extends 'website/base.html' %}
{% load static %}

{% block title %}
    Support Center
{% endblock %}

{% block styles %}
{% endblock %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col-md-8 py-4">
            <h1 class="curve-font mb-4">Tutest Support Center</h1>
            <h6 class="mb-3">Message Submitted Successfully...</h6>
            <h6 class="mb-3">Thanks for contacting us. Our support team will contact you as soon as possible..</h6>
        </div>
    </div>
{% endblock %}

templates/website/support-center.html
{% extends 'website/base.html' %}
{% load static %}

{% block title %}
    Support Center
{% endblock %}

{% block styles %}
{% endblock %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col-md-8 py-4">
            <form action="" method="post">
                {% csrf_token %}
                <h1 class="curve-font mb-4">Tutest Support Center</h1>
                <h3 class="mb-3">Submit A Request</h3>
                <select class="form-select mb-3" name="subject"  aria-label="Default select example" required>
                    <option name="subject" value="" selected disabled hidden>Select A Category</option>
                    <option name="subject" value="Account">Account</option>
                    <option name="subject" value="Services">Services</option>
                    <option name="subject" value="Reporting Bug">Reporting Bug</option>
                    <option name="subject" value="Others">Others</option>
                </select>
                <div class="mb-3">
                    <label for="emailInput" class="form-label"></label>
                    <input type="email" required name="email" class="form-control" id="emailInput" placeholder="Your Email ID">
                    <small>Please, enter the email address where you wish to receive our answer. If you are a registered
                        user of tutest, please include the email address you used when you registered if possible to
                        help us locate your account as soon as possible.</small>
                </div>
                <div class="mb-3">
                    <label for="userMessageInput" class="form-label"></label>
                    <textarea name="message" required class="form-control" id="userMessageInput" rows="7"
                              placeholder="Write us a message"></textarea>
                    <small>Please enter the details of your request and, if you have any questions regarding our Terms
                        of Use, please include specific samples of the usage you wish to give our resources. If you’re
                        reporting a problem, make sure to include as much information as possible. Please include any
                        screenshots or videos of issues since this will also help us resolve issues much sooner. Once
                        your request is submitted, a member of our support staff will respond as soon as
                        possible.</small>
                </div>
                <div class="text-center">
                    <button class="btn btn-success">Submit Request</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}