accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = "account"
urlpatterns = [
    path('sign-up/', views.signUpAs, name="sign-up-as"),
    # path('sign-up/instructor/', views.instructorSignUp, name="sign-up-as-instructor"),
    path('sign-up/tutee/', views.tuteeSignUp, name="sign-up-as-tutee"),
    path('sign-in/', LoginView.as_view(template_name='accounts/sign-in.html'), name="sign-in"),
    path('sign-out/', LogoutView.as_view(), name="sign-out"),
    path('forgot-password/', views.forgotPassword, name="forgot-password"),
    path('change-password/<token>', views.changePassword, name="change-password"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include("website.urls")),
    path('account/', include("accounts.urls")),
    path('instructor/', include("instructor.urls")),
    path('exam/', include("exam_app.urls")),
    path('tutee/', include("tutee.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exam_app/urls.py
from django.urls import path
from . import views

app_name = "exam_app"
urlpatterns = [
    path('create-exam/', views.createExam, name="create-exam"),
    path('instructors/all-exams/', views.viewAllExamsInstructors, name="view-all-exams-instructors"),
    path('edit-exam/<int:exam_id>/', views.editExam, name="edit-exam"),
    path('edit-exam/<int:exam_id>/add-question/', views.addQuestion, name="add-question"),
    path('edit-exam/<int:exam_id>/edit-question/<int:question_id>/', views.EditQuestion, name="edit-question"),
    path('tutee/all-exams/', views.viewAllExamsTutee, name="view-all-exams-tutee"),
    path('view-exam/<int:exam_id>/', views.viewExam, name="view-exam"),
    path('exam-summary/<int:exam_details_id>', views.examSummary, name="exam-summary"),
    path('exam-result/<int:exam_details_id>', views.examResult, name="exam-result"),
    path('exam-results-list/<int:exam_id>', views.examResultsList, name="tutee-exam-results-list"),
    path('<int:exam_details_id>/view_question_result/<int:question_details>', views.questionResult,
         name="question-result"),
    path('edit-exam/edit-details/<int:exam_id>', views.editExamDetails, name="edit-details"),
    path('instructor/<int:exam_id>/results/', views.viewAllDetails, name="instructor-details"),
    path('instructor/<int:exam_id>/results/<int:exam_details_id>', views.tuteeExamDetails, name="tutee-exam-results"),
    path('exam/<int:exam_details_id>/evaluation/<int:question_details_id>', views.questionEvaluation,
         name='question-evaluation'),
    path('edit-exam/<int:exam_id>/add-section/', views.addSection, name="add-section"),
    path('edit-exam/<int:exam_id>/edit-section/<int:section_id>', views.editSection, name="edit-section"),
    path('edit-exam/<int:exam_id>/section/<int:section_id>/add-question', views.sectionAddQuestion,
         name="section-add-question"),
    path('edit-exam/<int:exam_id>/section/<int:section_id>/edit-question/<int:question_id>', views.sectionEditQuestion,
         name="section-edit-question"),
    path('<int:exam_id>/<int:section_index>/<int:question_index>', views.takeExamSection, name="take-exam-section"),
]

instructor/urls.py
from django.urls import path
from . import views

app_name = "instructor"
urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard"),
]

tutee/urls.py
from django.urls import path
from . import views

app_name = "tutee"
urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard"),
]

website/urls.py
from django.urls import path
from . import views

app_name = "website"
urlpatterns = [
    path('', views.index, name="index"),
    path('support-center/', views.supportCenter, name="support-center"),
    path('support-center/success', views.supportCenterSuccess, name="support-center-success"),
    path('permission-denied', views.permissionDenied, name="permission-denied")

]

instructor/models.py
from django.db import models

# Create your models here.

instructor/views.py
from django.shortcuts import render


# Create your views here.
def dashboard(request):
    return render(request, 'instructor/dashboard.html')

templates/instructor/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
    {% endblock %}</title>
    <meta http-equiv="refresh" content="30">
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon_io/favicon.ico' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block styles %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand sticky-top">
        <div class="container-xxl px-3">
            <a class="navbar-brand" href="{% url 'website:index' %}">
                <img src="{% static 'images/light-logo.png' %}" alt="Tutest Logo" height="57px" width="137px">
            </a>
            <ul class="navbar-nav ms-auto align-items-center">
                {#<li class="nav-item"><a class="nav-link mx-2" href="#">Features</a></li>#}
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="true">
                        <button class="btn btn-light profile-btn" type="button">{{ user.username.0.upper }}</button>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li class="text-end px-3"><strong>Hi, {{ user.first_name }}</strong></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li class=text-end px-3
                        "><a class="dropdown-item" href="{% url 'account:sign-out' %}">Sign out</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
    <main class="container-xxl px-3">
        {% block body %}
        {% endblock %}
    </main>
    <footer>
        <div class="container-xxl p-3 text-center">
            <small class="footer-copyright">&copy; TUTEST 2022</small>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
</body>
</html>

templates/instructor/dashboard.html
{% extends 'instructor/base.html' %}

{% block title %}
    Tutest - {{ user.username }} Dashboard
{% endblock %}

{% block styles %}
{% endblock %}

{% block body %}
    <div class="p-md-5 p-3">
        <h6><strong>Welcome {{ user.first_name }} {{ user.last_name }}</strong></h6>
        <hr>
        <a href="{% url 'exam_app:create-exam' %}">
            <button type="button" class="btn btn-success">Create Exam</button>
        </a>
        <a href="{% url 'exam_app:view-all-exams-instructors' %}">
            <button type="button" class="btn btn-primary ms-2">View Exams</button>
        </a>
        <hr>
    </div>
{% endblock %}